services:
  db:
    image: postgres:latest
    container_name: swift_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: ./swift_app
    container_name: swift_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./swift_app:/app/swift_app


volumes:
  postgres_data: